# Aviso: Algumas das configurações não foram revisadas após a publicação do trabalho, então podem estar desatualizadas

quarkus.application.name=ads-forms
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# DataSource (prod/local)
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:mariadb://localhost:3306/adsforms}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:adsforms}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:adsforms}
quarkus.datasource.jdbc.max-size=16

# DevServices
quarkus.datasource.devservices.enabled=false

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger

# Logging
quarkus.console.color=true
quarkus.log.category."xq.yiesko.forms".level=INFO